services:
  sample-kafka-producer:
    container_name: sample-kafka-producer
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
