apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-dashboard
  labels:
    app: sample-kafka-producer
  name: sample-kafka-producer
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sample-kafka-producer
  type: ClusterIP